import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { z } from "zod";
import { AuthPage } from "@/components/auth-page";
import { registerDemo } from "@/lib/remargin";

export const Route=createFileRoute("/register")({head:()=>({meta:[{title:"Register your factory — ReMargin"},{name:"description",content:"Create a ReMargin workspace for your CNC manufacturing company."},{property:"og:title",content:"Register — ReMargin"},{property:"og:description",content:"Create your factory sustainability workspace."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Register});
const schema=z.object({name:z.string().trim().min(3,"Enter your full name.").regex(/^[a-zA-Z .'-]+$/,"Name contains invalid characters."),email:z.string().email("Invalid email address."),password:z.string().min(8,"Use at least 8 characters.").regex(/[A-Z]/,"Add one uppercase letter.").regex(/[a-z]/,"Add one lowercase letter.").regex(/[0-9]/,"Add one number.").regex(/[^A-Za-z0-9]/,"Add one special character."),confirm:z.string(),company:z.string().trim().min(2,"Company name is required."),address:z.string().trim().min(8,"Enter the company address."),mobile:z.string().regex(/^[6-9]\d{9}$/, "Enter a valid 10-digit Indian mobile number.")}).refine(d=>d.password===d.confirm,{path:["confirm"],message:"Passwords do not match."});
function Register(){const nav=useNavigate();const [step,setStep]=useState(1);const [data,setData]=useState({name:"",email:"",password:"",confirm:"",company:"",address:"",mobile:""});const [errors,setErrors]=useState<Record<string,string>>({});const strength=useMemo(()=>[data.password.length>=8,/[A-Z]/.test(data.password),/[a-z]/.test(data.password),/\d/.test(data.password),/[^A-Za-z0-9]/.test(data.password)].filter(Boolean).length,[data.password]);function update(k:string,v:string){setData({...data,[k]:v});setErrors({...errors,[k]:""});}function next(){const fields=step===1?["name","email","password","confirm"]:["company","address","mobile"];const parsed=schema.safeParse(data);const map:Record<string,string>={};if(!parsed.success)parsed.error.issues.forEach(i=>map[String(i.path[0])]=i.message);const relevant=fields.some(f=>map[f]);if(relevant){setErrors(map);return;}if(step===1)setStep(2);else{registerDemo({name:data.name,email:data.email,company:data.company,address:data.address,mobile:data.mobile});nav({to:"/login"});}}return <AuthPage title="Create your workspace" subtitle={`Step ${step} of 2 · ${step===1?"Account details":"Company details"}`}><div className="mb-8 grid grid-cols-2 gap-2"><span className="h-1 rounded-full bg-primary"/><span className={`h-1 rounded-full ${step===2?"bg-primary":"bg-border"}`}/></div><div className="space-y-4">{step===1?<>{field("Full name","name",data,update,errors)}{field("Gmail / email","email",data,update,errors,"email")}{field("Password","password",data,update,errors,"password")}<div><div className="flex gap-1">{[1,2,3,4,5].map(i=><span key={i} className={`h-1 flex-1 rounded-full ${i<=strength?"bg-primary":"bg-border"}`}/>)}</div><p className="mt-1 text-[10px] text-muted-foreground">Password strength: {strength<3?"weak":strength<5?"good":"strong"}</p></div>{field("Confirm password","confirm",data,update,errors,"password")}</>:<>{field("Company name","company",data,update,errors)}<label className="block"><span className="form-label">Company address</span><textarea className="form-input min-h-24" value={data.address} onChange={e=>update("address",e.target.value)}/>{errors.address&&<p className="mt-1 text-xs text-destructive">{errors.address}</p>}</label>{field("Mobile number","mobile",data,update,errors,"tel")}</>}<div className="flex gap-3 pt-3">{step===2&&<button className="button-secondary flex-1" onClick={()=>setStep(1)}>Back</button>}<button className="button-primary flex-1" onClick={next}>{step===1?"Continue":"Create account"}</button></div><p className="text-center text-sm text-muted-foreground">Already registered? <Link to="/login" className="font-bold text-primary">Login</Link></p></div></AuthPage>}
function field(label:string,key:string,data:Record<string,string>,update:(k:string,v:string)=>void,errors:Record<string,string>,type="text"){return <label className="block"><span className="form-label">{label}</span><input className="form-input" type={type} value={data[key]} onChange={e=>update(key,e.target.value)}/>{errors[key]&&<p className="mt-1 text-xs text-destructive">{errors[key]}</p>}</label>}