import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { CheckCircle2, FileImage, FileText, ScanLine, UploadCloud, X } from "lucide-react";
import { useState } from "react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { demoSession, mockApi } from "@/lib/remargin";

export const Route=createFileRoute("/upload")({head:()=>({meta:[{title:"Upload Factory Data — ReMargin"},{name:"description",content:"Upload and verify energy, scrap and electricity records."},{property:"og:title",content:"Upload Factory Data — ReMargin"},{property:"og:description",content:"Photo-first factory data capture and verification."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:UploadPage});
function UploadPage(){const nav=useNavigate();const [start,setStart]=useState("");const [end,setEnd]=useState("");const [input,setInput]=useState("");const [output,setOutput]=useState("");const [scrap,setScrap]=useState("");const [files,setFiles]=useState<Record<string,string>>({});const [processing,setProcessing]=useState(false);const energy=Number(end)-Number(start);const yieldValue=Number(input)>0?(Number(output)/Number(input))*100:0;const invalid=start!==""&&end!==""&&energy<0;function file(name:string,file?:File){if(file)setFiles({...files,[name]:file.name});}async function process(){if(invalid)return;setProcessing(true);await mockApi.processUpload(demoSession.companyId,{start,end,input,output,scrap,files});nav({to:"/result"});}return <AppShell><PageHeader eyebrow="Data capture" title="Upload Factory Data" description="Photograph records or enter values manually. Every extracted value stays editable until you verify it."/><div className="grid gap-5 xl:grid-cols-3"><UploadSection icon={ScanLine} title="Energy Meter Scan" description="Start and end meter readings"><Dropzone name="meter" file={files.meter} onFile={file}/><div className="grid grid-cols-2 gap-3"><Field label="Start unit" value={start} set={setStart}/><Field label="End unit" value={end} set={setEnd}/></div>{invalid?<p className="text-xs text-destructive">End meter reading cannot be lower than start reading.</p>:energy>=0&&start&&end?<Result label="Energy used" value={`${energy.toLocaleString()} kWh`}/>:null}</UploadSection><UploadSection icon={FileImage} title="Scrap & Production Data" description="Production slip or manual values"><Dropzone name="scrap" file={files.scrap} onFile={file}/><label className="block"><span className="form-label">Input material</span><input className="form-input" placeholder="EN8 Steel"/></label><div className="grid grid-cols-3 gap-2"><Field label="Input kg" value={input} set={setInput}/><Field label="Output kg" value={output} set={setOutput}/><Field label="Scrap kg" value={scrap} set={setScrap}/></div>{yieldValue>0&&<Result label="Calculated yield" value={`${yieldValue.toFixed(1)}%`}/>}</UploadSection><UploadSection icon={FileText} title="Electricity Bill" description="Image or PDF upload"><Dropzone name="bill" file={files.bill} onFile={file}/><label className="block"><span className="form-label">Billing period</span><input type="month" className="form-input"/></label><div className="grid grid-cols-2 gap-3"><Field label="Units consumed" value="" set={()=>{}}/><Field label="Amount ₹" value="" set={()=>{}}/></div></UploadSection></div><div className="mt-6 flex flex-col items-end gap-2 pb-20 lg:pb-0"><button className="button-primary min-w-48" onClick={process} disabled={processing}>{processing?"Processing data…":"Process Data"}</button><p className="text-xs text-muted-foreground">OCR is simulated in this demonstration. Verify all values before processing.</p></div></AppShell>}
function UploadSection({icon:Icon,title,description,children}:{icon:typeof ScanLine;title:string;description:string;children:React.ReactNode}){return <section className="panel space-y-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-secondary text-primary"><Icon size={20}/></span><div><h2 className="font-display font-bold">{title}</h2><p className="text-xs text-muted-foreground">{description}</p></div></div>{children}</section>}
function Dropzone({name,file,onFile}:{name:string;file?:string;onFile:(name:string,file?:File)=>void}){return <label className="flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-md border border-dashed border-primary/40 bg-secondary/40 p-4 text-center">{file?<><CheckCircle2 className="text-success"/><span className="mt-2 text-xs font-bold">{file}</span><span className="mt-1 text-[10px] text-muted-foreground">Ready for OCR verification</span></>:<><UploadCloud className="text-primary"/><span className="mt-2 text-xs font-bold">Drop or browse file</span><span className="mt-1 text-[10px] text-muted-foreground">JPG, PNG or PDF</span></>}<input className="hidden" type="file" accept="image/*,.pdf" onChange={e=>onFile(name,e.target.files?.[0])}/></label>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block"><span className="form-label">{label}</span><input className="form-input" type="number" min="0" value={value} onChange={e=>set(e.target.value)}/></label>}
function Result({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between rounded-md bg-success-soft px-3 py-2 text-xs"><span>{label}</span><strong>{value}</strong></div>}